swagger: "2.0"
info:
  description: "Simple doc for getting orders Activity 3.3 CST-339"
  version: "1.0.0"
  title: "3.3 Orders"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "me@yourhouse.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8080"
basePath: "/service"
tags:
- name: "orders"
  description: "Go get me a list of orders"
schemes:
- "http"
paths:
  /getJson:
    get:
      tags:
      - "orders"
      summary: "Returns an OrderList in JSON format"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Success"
  /getXml:
    get:
      tags:
      - "orders"
      summary: "Returns an OrderList in XML Format"
      description: "Multiple status values can be provided with comma separated strings"
      responses:
        "200":
          description: "Success"
definitions:
  Order:
    type: "object"
    properties:
      id:
        type: "number"
      orderNo:
        type: "string"
      productName:
        type: "string"
      price:
        type: "number"
      quantity:
        type: "integer"
    xml:
      name: "Order"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"